try with actually running container this create looks suspicious

diff --git a/ci/build-in-docker b/ci/build-in-docker
--- a/ci/build-in-docker
+++ b/ci/build-in-docker
@@ -24,11 +24,22 @@ container=${prefix}-${timestamp}-cont
 
 # Builds here (if fails then no image is here = nothing to clean up)
 docker build --tag ${image} --file Dockerfile .
-# unlikely to fail at all
-docker create --name ${container} ${image}
+
+# rm -fr ${dst_path}
+# rm -fr ${dst_path}
+
+# this can fail due to 
+if docker run -rm --name ${container} ${image}; then
+  echo "💚 Docker container started successfully"
+else
+  echo "💔 Error starting Docker container"
+  exit_status=$?
+  docker rm ${container}
+  docker rmi ${image}
+  exit $exit_status
+fi
 
 # This can fail due to misconf, and needs cleanup
-rm -fr ${dst_path}
 if docker cp ${container}:${src_path} ${dst_path}; then
   echo "💚 File copied successfully"
 else
@@ -39,6 +50,7 @@ else
   exit $exit_status
 fi
 
+docker stop ${container}
 docker rm ${container}
 docker rmi ${image}
 
